 <!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>PHP PostgreSQL</title>
	<link rel="stylesheet" href="css/materialize.min.css">
	<link rel="stylesheet" href="css/icon.css">
	<script src="js/jquery-1.12.4.min.js"></script>
  <script src="js/materialize.min.js"></script>
</head>
<body>
 <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Sass</a></li>
        <li><a href="#">Components</a></li>
        <li><a href="#">JavaScript</a></li>
      </ul>
    </div>
  </nav>